[package]
name = "command17/rbxsignal"
version = "1.0.1"
description = "Basic Signal class"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
autors = ["@baum1000000 (baum, Command17)"]
realm = "shared"

[dependencies]
